project:
  type: website

website:
  title: "Just an Economist"
  navbar:
    right:
      - index.qmd 
      - blog.qmd
      - icon: github
        href: https://github.com/
      - icon: LinkedIn
        href: https://linkedin.com

format:
  html:
    theme: flatly
    mainfont: system-ui
    css: styles.scss
