project:
  type: website

website:
  title: "Tiago Souza"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: flatly
    css: styles.css
