---
layout: post
title: "Economics - A Personal Statement"
#date: 
#description: 
#img:  
---

This is a personal statement about what makes me love economics so deeply.

The most important lesson I learned a few years ago is that Economics studies people, how they behave and how we economists, as social scientists, try to understand the main drivers of people's choices. In some sense, it becomes a fun quest to find what motivates shoppers to buy a product, citizens to abide by the rules of where they reside or burglars to commit wrongdoings, children to obey their parents or parents thinking about a second child, policymakers to propose laws that will benefit the general population or their chances for reelection... The list goes on and on. Whenever people are making choices, Economics can provide one point of view. As Gabry Becker put very well in his "Economic Aproach to Human Behavior", Economics is a set of tools that can shed light on social phenomena from a perspective different than other social sciences as Psychology, Anthropology, History, Sociology.

Economics is about weighing benefits and costs, but the cost is not necessarily the price announced or the one you see on the shelves. Often times costs are subjective, called shadow price. One does not know exactly how much she would pay for a bus on a rainy day, but it is certainly more that the ticket accquired. Economists can have a grasp of this value based on behavior and people's choices and that is one of the reasons I find empirical work crucial for Economics. It creates the bridge between what we expect from models and the real world, serving as a reality check.

We often rely on models to reach conclusions, but there are two dimensions that economists should pay special attention to before making bold statments. The first layer is to ask if that model is suited to understand the problem at hand by making sure that it contains the correct drivers of behavior. Without that, one might be looking to the weather to determine what people will watch on television (which might even have an influence, but should not be the determining factor). However, even with the understanding of the main drivers of behavior, an economist should always give a second step and question whether there are other aspects of life influencing people's choices in that particular setting. Putting differently, being aware of the limitations that a model has in providing guidance to understand behavior and to serve as a guidance for policy.