---
layout: post
title: "Economics - My personal view"
#date: 
#description: 
#img:  
---

This is a personal statement about what makes me love economics so deeply.

The most important lesson I learned a few years ago is that Economics studies people, how they behave and how we economists, as social scientists, can try to understand the main drivers of people's choices. In some sense, it becomes a fun quest to find what motivates shoppers to buy a product or choose something else, citizens to abide by the rules of where they reside or burglars to commit their wrongdoings, children to obey their parents or parents thinking about a second child, policymakers to propose laws that will benefit the general population or their change for reelection... The list goes on and on. Whenever people are making choices, Economics can try to its point of view. As Gabry Becker put very well in him "Economic Aproach to Human Behavior", Economics is a set of tools that can shed light on social phenomena from a different perspective than other social sciences as Psychology, Anthropology, History, Sociology.

Economics is about weighing benefits and costs, but the cost is not ncessarily the price announced or the one you see on the shelves. That is

We often rely on models to reach conclusions, but there are two dimensions that economists should pay special attention to before making bold statments. The first layer is to ask if that model is suited to understand the problem at hand by making sure that it contains the correct drivers of behavior. Without that, one might be looking to the weather to determine what people will watch on television (which might even have an influence, but should not be the determining factor). However, even understanding the main drivers of behavior, an economist should always give a second step and question whether there are other aspects of life influencing people's choices in that particular setting, putting differently, being aware of the limitations that a model has in providing guidance to understand behavior and to serve as a guidance to policy.